[package]
name = "pwcc"
version = "0.0.10"
edition = "2024"

[dependencies]
functional = { path = "../functional" }
functional_macros = { path = "../functional_macros" }
pwcc_util = { path = "../pwcc_util" }
miette = "7.5"
regex = "1.11.*"
thiserror = "2.0"
